repos :
- repo : https :// github . com / astral - sh / ruff - pre - commit
rev : v0 .9.5
hooks :
- id : ruff # Linter
args : [ - - fix ] # Automatyczne poprawki b ł ę d ó w
- id : ruff - format # Formatter
